# Generated by Django 4.2.26 on 2025-11-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='skill_set',
        ),
    ]
