# Generated by Django 4.2.26 on 2025-11-16 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationassigneduserstatuses',
            name='assigned_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_application_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationassigneduserstatuses',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assignments', to='applications.applicationstatuses'),
        ),
    ]
