# Generated by Django 4.2.26 on 2025-11-15 08:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_applications_skill_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='linkdin',
            new_name='linkedin',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='resume_content_type',
        ),
        migrations.AddField(
            model_name='applications',
            name='current_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_applications', to='applications.applicationstatuses'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='current_ctc',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='applications',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='applications',
            name='expected_ctc',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='applications',
            name='phone_no',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian phone number (e.g. 9876543210 or +919876543210).', regex='^(?:\\+91)?[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='applications',
            name='zip_code',
            field=models.CharField(default=458118, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter valid 6-digit PIN code')]),
            preserve_default=False,
        ),
    ]
