# Generated by Django 4.2.26 on 2025-11-15 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
        ('applications', '0003_rename_linkdin_applications_linkedin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationassigneduserstatuses',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='applicationassigneduserstatuses',
            name='application_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.applications'),
        ),
        migrations.AlterField(
            model_name='applicationassigneduserstatuses',
            name='assigned_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_application_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationassigneduserstatuses',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assignments', to='applications.applicationstatuses'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobs'),
        ),
    ]
