# Generated by Django 4.2.26 on 2025-11-15 10:56

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_applicationassigneduserstatuses_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatuses',
            name='order_sequence',
            field=models.IntegerField(db_index=True, editable=False),
        ),
        migrations.AddConstraint(
            model_name='applicationstatuses',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('order_sequence',), name='unique_order_sequence'),
        ),
    ]
